### ISSUE TITLE
Examples for UV.queue_work?

### ISSUE THREAD

**Issue by Asmod4n** [mattn/mruby-uv#57]
couldn't get UV.queue_work to work by reading the source.

Thought it works like this:
```ruby
UV.queue_work(lambda { 2 + 2 }) do |result|
  puts result
end
```

But its complaining about the lambda, same goes for Proc.new or proc {}.

**Comment by take-cheeze** [comment]
The argument of `UV.queue_work` can only take C function `Proc`
since it may modify mruby resource in other thread.
Use mruby-thread instead.
